### ISSUE TITLE
package.json generated by framework7-cli@4.0.0 incorrect

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7-cli#115]
framework7 create --ui
> only pickup "Simple web app" then "CREATE APP"
got package.json
```
"dependencies": {
    "dom7": "^3.0.0",
    "framework": "0.0.0",
    "framework7-icons": "^3.0.1",
    "skeleton-elements": "^3.3.0",
    "swiper": "^6.4.5"
  },
```

npm run start
>
```
ERROR in ./src/pages/form.f7.html 14:0-34
Module not found: Error: Can't resolve 'framework7' in '/Users/orz99/zoo/bcq-web/src/pages'
```

![image](https://user-images.githubusercontent.com/981381/103416312-0a638e00-4bc1-11eb-86a0-c646d993fd36.png)

![image](https://user-images.githubusercontent.com/981381/103416325-1cddc780-4bc1-11eb-9304-43556f8d4981.png)

**Comment by nolimits4web** [comment]
Fixed in 4.0.1
