### ISSUE TITLE
ERROR in ./src/css/framework7-custom.less (framework7-cli@4.0.2)

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7-cli#120]
framework7 custom build ERROR

got `Module build failed (from ./node_modules/less-loader/dist/cjs.js)` ERROR When Framework7 Custom Build Enabled

![image](https://user-images.githubusercontent.com/981381/103436112-3a5b7180-4c53-11eb-921d-7faf681f1452.png)

**Comment by AlwaysLoveme** [comment]
same problem!

**Comment by nolimits4web** [comment]
As a workaround downgrade less to 3.x
```
npm I less@3
```

**Comment by yelban** [comment]
It's work! Thanks a lot.
