### ISSUE TITLE
Some optimizations for Cordova (Plugin and config.xml)

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-cli#125]
1) The `cordova-plugin-splashscreen` is installed for both iOS and Android, but starting from version 6.0.0 of Cordova for iOS it is integrated.

https://github.com/framework7io/framework7-cli/blob/aff201020be4d5450af925a91eda42ebf8b5fc47/create/utils/get-options.js#L284-L290

https://cordova.apache.org/news/2020/06/13/plugins-release.html

> Splash Screen
> In the Cordova-iOS 6.x platform, the splash screen feature has been integrated into its core and no longer needs this plugin. This release prevents the plugin from being added to the iOS 6.x platform.
> 
> GH-261 chore: add cordova-ios requirement <6.0.0

2) Some improvements that could be made to these lines of the `config.xml` file which are added to all platforms:

https://github.com/framework7io/framework7-cli/blob/aff201020be4d5450af925a91eda42ebf8b5fc47/create/templates/generate-config-xml.js#L84-L91

`<preference name="BackupWebStorage" value="local" />` is _only_ for **iOS**

`<preference name="ShowSplashScreenSpinner" value="false" />` is _only_ for **Android** (in the version of _splashscreen_ integrated in Cordova for iOS it seems to be no longer there)

`<preference name="Suppresses3DTouchGesture" value="true" />` is _only_ for **iOS**

`<preference name="Allow3DTouchLinkPreview" value="false" />` it was for _cordova-plugin-wkwebview-engine_, which has now been removed

`<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />` is _only_ for **iOS**

`<preference name="AllowInlineMediaPlayback" value="true" />` is _only_ for **iOS**

https://cordova.apache.org/docs/en/latest/config_ref/index.html#preference

Thanks.

**Comment by nolimits4web** [comment]
There is nothing to do with it, if some preferences/plugin is added for both platforms but supported only by specific platform, it will be picked up correctly, and just ignored by other platform
