### ISSUE TITLE
Select version when using framework7-cli create command

### ISSUE THREAD

**Issue by leandroparedes** [framework7io/framework7-cli#126]
Is there a way to create a Framework7 project with a previous version using the framework7-cli?

Currently `framework7 create` creates a v6.0.3 project but I need to create a v5 project

**Comment by DAnn2012** [comment]
Hello @leandroparedes ,
I think that to create a v5 project you need to install the 3.4.5 version of framework7-cli:

`$ npm install -g framework7-cli@3.4.5`

But this is the command to install it globally.

Then, to avoid checking for CLI updates, you can run command with `--skipUpdate` flag:

`$ framework7 create --skipUpdate`
