### ISSUE TITLE
Installation issue: sudo npm install -g framework7-cli

### ISSUE THREAD

**Issue by vimkaf** [framework7io/framework7-cli#136]
I have been facing this error for the past month now and i have tried everything i know, the installtion doesnt pass this stage
``npm WARN deprecated opn@6.0.0: The package has been renamed to open
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
**npm ERR! path /home/kay/Documents/lib/node_modules/framework7-cli/node_modules/sharp**
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-28T10_15_18_829Z-debug.log
``
HELP!!

**Comment by vimkaf** [comment]
i detected that the problem is coming installing the sharp package..i tried to install it seperately i still got this error
`npm ERR! code 1
npm ERR! path /home/kay/Documents/lib/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kay/.npm/_logs/2021-02-28T14_08_39_045Z-debug.log
`
`command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node `install/dll-copy)`
The above command keeps failing
how can i solve this issue??

**Comment by vimkaf** [comment]
@Cidro @nolimits4web @DAnn2012 @srbala can any of you guys help on this ..i'm dont have too much time ..i need the cli working asap.

**Comment by srbala** [comment]
@vimkaf error info above does not give much information. What is the OS, npm version, framework7 version etc.

Tried with node 12.12.x, npm 6.14.x, framework 4.0.7 worked on Mac 10.15.7

**Comment by vimkaf** [comment]
Here you go
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Memory: 2.86 GB / 9.61 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
    NPM Version: 7.5.3

**Comment by srbala** [comment]
what do mean by `Container: Yes`,  npm installer tries to build some packages, it needed proper development packages installed. check the original source https://github.com/libvips/libvips for proper dependency.

```
command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
```

**Comment by vimkaf** [comment]
i think it is the sharp library that's causing this issue, it also requires libvips , which i have already opened an issue and i was told "For npm v7 support, framework7-cli needs to update to the latest version of sharp, currently v0.27.2".

**Comment by srbala** [comment]
sharp library is used resize images, which uses libvips. Can you use the npm v6?

**Comment by srbala** [comment]
Alternate  would be upgrading necessary packages in your framework-cli fork.

**Comment by vimkaf** [comment]
so i need to downgrade the npm version ...which exact version (https://www.npmjs.com/package/npm?activeTab=versions) of 6 do you want me to install

**Comment by srbala** [comment]
you can use `nvm` for node package management. try using Node 12.x LTS which will give you npm 6.x. nvm gives you the ability to switch between multiple versions of node as your development needs.

**Comment by srbala** [comment]
https://github.com/nvm-sh/nvm

**Comment by srbala** [comment]
@vimkaf is your issue resolved?  Please close thread, if resolved

**Comment by vimkaf** [comment]
It hasn't been resolved yet. I forked it as you suggested but I'm still
getting the same error

**Comment by vimkaf** [comment]
It is working now..all i did was to install node v12.x  and rerun npm install -g framework7-cli..it worked like a charm.
Thanks.

**Comment by maqeelqureshi** [comment]
It worked for me after installing node-v12.21.0-x86.
