### ISSUE TITLE
Error on dependency installation

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-cli#142]
While installation with F7 Svente + Capacitor + Single View I get the following error on latest MacOS:

    Framework7 CLI UI is running on http://localhost:3001 (CTRL + C to exit)
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    npm ERR! code 1
    npm ERR! path /Users/Max/Documents/GitHub/f7-svente-contacts/node_modules/sharp
    npm ERR! command failed
    npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
    npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
    npm ERR!   LIBTOOL-STATIC Release/nothing.a
    npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
    npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
    npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-x64.tar.br
    npm ERR! node:internal/fs/utils:323
    npm ERR!     throw err;
    npm ERR!     ^
    npm ERR! 
    npm ERR! Error: EACCES: permission denied, copyfile '/var/folders/fq/9m2wwb_n67l9zb04q4mp7nhr0000gn/T/3589-libvips-8.10.5-darwin-x64.tar.br' -> '/Users/Max/.npm/_libvips/libvips-8.10.5-darwin-x64.tar.br'
    npm ERR!     at Object.copyFileSync (node:fs:2068:3)
    npm ERR!     at WriteStream.<anonymous> (/Users/Max/Documents/GitHub/f7-svente-contacts/node_modules/sharp/install/libvips.js:133:16)
    npm ERR!     at WriteStream.emit (node:events:369:20)
    npm ERR!     at emitCloseNT (node:internal/streams/destroy:169:10)
    npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:80:21) {
    npm ERR!   errno: -13,
    npm ERR!   syscall: 'copyfile',
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/var/folders/fq/9m2wwb_n67l9zb04q4mp7nhr0000gn/T/3589-libvips-8.10.5-darwin-x64.tar.br',
    npm ERR!   dest: '/Users/Max/.npm/_libvips/libvips-8.10.5-darwin-x64.tar.br'
    npm ERR! }
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.2
    npm ERR! gyp info using node@15.13.0 | darwin | x64
    npm ERR! gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
    npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/Max/Documents/GitHub/f7-svente-contacts/node_modules/sharp/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/Max/Library/Caches/node-gyp/15.13.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/Max/Library/Caches/node-gyp/15.13.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/Max/Library/Caches/node-gyp/15.13.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/Max/Documents/GitHub/f7-svente-contacts/node_modules/sharp',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
    npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
    npm ERR! #include <vips/vips8>
    npm ERR!          ^~~~~~~~~~~~
    npm ERR! 1 error generated.
    npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    npm ERR! gyp ERR! System Darwin 20.3.0
    npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /Users/Max/Documents/GitHub/f7-svente-contacts/node_modules/sharp
    npm ERR! gyp ERR! node -v v15.13.0
    npm ERR! gyp ERR! node-gyp -v v7.1.2
    npm ERR! gyp ERR! not ok

**Comment by scriptPilot** [comment]
Same error when running the CLI with `sudo`.

**Comment by scriptPilot** [comment]
When I try to run `npm install && npm run postinstall` to complete the broken installation, it fails due to missing command `cpy` ...

**Comment by scriptPilot** [comment]
Same issue when I run the CLI within terminal instead UI with `sudo` first.

**Comment by scriptPilot** [comment]
There is no issue, when I uncheck Capacitor and install only Framework7 Svelte.

**Comment by nolimits4web** [comment]
According to your error log, you have some access errors. Closing as not related to F7 CLI
