### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v6.0.0/win32-x64-64_binding.node":

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7-cli#154]
When I choose SCSS/SASSS, there is an error on the terminal saying its 404

**Comment by johndavemanuel** [comment]
@nolimits4web  I check the repo releases and there is no file like this

win32-x64-64_binding.node

https://github.com/sass/node-sass/releases

**Comment by DAnn2012** [comment]
Hi @johndavemanuel 

you have already taken a look at this link [https://github.com/sass/node-sass/issues/2773](https://github.com/sass/node-sass/issues/2773) and if what is written also solves your error?

**Comment by johndavemanuel** [comment]
@DAnn2012 I have not seen it yet. let me see if it solves my issue. thanks
