### ISSUE TITLE
f7 cli with --ui generates whitespace in Cordova app

### ISSUE THREAD

**Issue by ghost** [framework7io/framework7-cli#16]
Creating a single view Cordova app with f7 cli --ui creates whitespace at the bottom of the app after `cordova build ios` in iPhone7 and iPhone X.

**Comment by srbala** [comment]
@vg0x01  Please update framework7-cli and retry this issue and post an update. possibily screen capture before and after the issue the command.

**Comment by srbala** [comment]
@nolimits4web Please close this issue, no response from user and no longer exists
