### ISSUE TITLE
Can't create app with latest Capacitor

### ISSUE THREAD

**Issue by jzraibi** [framework7io/framework7-cli#162]
@nolimits4web

the create script (cli & ui) does not complete and exits with error while creating capacitor app
I tried it (many times) on **windows and mac** and even i tried it with **a completely new environement**. the result is same:
**Error: Shell command exit with non zero code: 1**
this started to happen with the **launch of capacitor 3.0**
![image](https://user-images.githubusercontent.com/6017542/121020319-ef68fb80-c7a8-11eb-982b-5c3b3440cf3f.png)

**Comment by nirajkaushal** [comment]
I am also facing same issue when I run `framework7 create`. @nolimits4web

**Comment by binaryelites** [comment]
any work around regarding this?

**Comment by maccman** [comment]
Same

**Comment by nolimits4web** [comment]
Should be fixed in 4.1.0

**Comment by jzraibi** [comment]
Yes now it's fixed. thanks a lot Vladimir @nolimits4web
