### ISSUE TITLE
Cordova Android 11.0.0 and the SplashScreen plugin

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-cli#194]
Hello @nolimits4web 

With the latest version of [Cordova Android (11.0.0)](https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html) the SplashScreen plugin has been integrated into the core, as has already happened with Cordova iOS.

I think it is necessary to make some adjustments in the creation of the Cordova projects for Android with the framework7 cli, when using cordova-android@11.x or later.

Thanks.

**Comment by DAnn2012** [comment]
Hello @nolimits4web 

as soon as you can, could you take a look at this problem?

Thanks.

**Comment by DAnn2012** [comment]
Hi @nolimits4web 

Thank you for noticing this issue request of mine.

Don't you think it's appropriate to also make changes to the "`config.xml`" file and the "`/create/templates/common/cordova-res/screen/android/`" folder as described in the links on this following page?

https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html

Thanks.

**Comment by nolimits4web** [comment]
What changes?

**Comment by DAnn2012** [comment]
I refer to these to support Android 12 Splash Screen API and backwards compatibility:

https://github.com/apache/cordova-android/pull/1441

https://github.com/apache/cordova-android/pull/1441/files#diff-d763ad63100202003897844283a75759b21b2e83221de64f80fd7e238bebcda6

Thanks.

**Comment by Simone4e** [comment]
The method complete change the `<splash>` tag is outdated.
