### ISSUE TITLE
Add cordova electron

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7-cli#23]
Добрый день! Cordova выпустила в 9 версии поддержку electron. 
Предлагаю добавить в CLI его поддержку при наличии целесообразности.

**Новость:**
https://cordova.apache.org/announcements/2019/03/18/cordova-electron-release-1.0.2.html

**Comment by nolimits4web** [comment]
Добрый день! Это есть в планах, добавлю в ближайших апдейтах
