### ISSUE TITLE
Create a folder for new App

### ISSUE THREAD

**Issue by Samnan** [framework7io/framework7-cli#25]
Hi,

   I think there should be a checkbox on the create ui that says "Create folder for the app". I installed framework7-cli and in my projects folder run `framework7 create --ui`, and when i pressed the button, it created all folders within my main projects folder (which was unexpected). Either that or make the first text box for the project path to be editable so the complete path can be typed in for the project?

**Comment by nolimits4web** [comment]
Fixed in 2.3.0
