### ISSUE TITLE
Optimize F7 Build

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-cli#33]
First of all thank you for this great CLI :-)

On initial creation, there a a lot of choices to be taken, but not in all details I know what I will need in the end (which modules for example). Is there a way to update the F7 build later according these modules I really used? Maybe an automatic scan of the app files can be a solution and can be a fixed part of the final build process.

**Comment by nolimits4web** [comment]
> Is there a way to update the F7 build later according these modules I really used? Maybe an automatic scan of the app files can be a solution and can be a fixed part of the final build process.

Would be great of course, but no chances, sorry :) This will require:

1) To disallow you to edit f7 custom build files
2) Or to analyze all of your code and find what and where need to be changed. <- this is close to impossible or will require unbelievable amount of time to implement 😊
