### ISSUE TITLE
Webpack Bundle Size Warning

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-cli#36]
While production build (with iOS + MD Themes / Tab Template), Webpack complains about the bundle size:

> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>   css/app.3dbf5a.css (433 KiB)
>   js/app.3dbf5a.js (985 KiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (1.38 MiB)
>       css/app.3dbf5a.css
>       js/app.3dbf5a.js
> 
> 
> WARNING in webpack performance recommendations: 
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by nolimits4web** [comment]
Warning is not the error. Use custom build technics to decrease bundle size by including only required modules https://framework7.io/docs/custom-build.html
