### ISSUE TITLE
Failed to find 'ANDROID_HOME' environment variable.

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7-cli#39]
ERROR: 
Failed to find 'ANDROID_HOME' environment variable. Try setting it manually. Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

I follow this instructions carefully
https://www.fiznool.com/blog/2017/05/30/a-guide-to-installing-cordova-on-windows-10/

but it seems it still cannot find the variable, I already set in system and environment variables

EDIT: I can build cordova project alone like

```
cordova create cordova-hello-world
cd cordova-hello-world
cordova platform add android
cordova build
```

**Comment by nolimits4web** [comment]
Closing as not related to CLI
