### ISSUE TITLE
Error: Callback was already called. / Response status was 404

### ISSUE THREAD

**Issue by zkemppel** [framework7io/framework7-cli#4]
Getting the following error when trying to create a new project using `sudo f7 create myapp` on a Mac.  I uninstalled framework7-cli and cordova, and reinstalled without any warnings or errors; I still get this same issue.

![image](https://user-images.githubusercontent.com/13770368/35024032-6b92342e-fb0b-11e7-99ac-e2c7892bb84b.png)

Most of the css files are showing up empty

![image](https://user-images.githubusercontent.com/13770368/35024185-1a7648d6-fb0c-11e7-91d7-49e1768a1aa5.png)

Index page looks like this with `f7 run`

![image](https://user-images.githubusercontent.com/13770368/35045766-e6487d20-fb62-11e7-96f8-d6ff1d9db747.png)

**Comment by pudjamansyurin** [comment]
same with this one, no solution yet

**Comment by gcortesm** [comment]
Aun sin solucion?

**Comment by a-j-n** [comment]
same here too with sudo and without

**Comment by neong** [comment]
For an hour looking solution. Bad luck. Here it's how I get it run. 
Go to http://framework7.io/templates/ to download the template you want and then download the framework7 master and copy the framework7/css/framework7.min.css into www

**Comment by kozmanbalint** [comment]
Check v2 branch. It is in line with f7 v4.
