### ISSUE TITLE
Label for "Fill style navigation bars" ui installation option potentially wrong

### ISSUE THREAD

**Issue by ww9** [framework7io/framework7-cli#43]
After running `framework7 create --ui` I see the label **Enables dark theme by default** under **Fill style navigation bars** checkbox:

![image](https://user-images.githubusercontent.com/27555162/61158401-ceb59f80-a4c6-11e9-8f12-b4f752fed6ed.png)

Clicking it doesn't seem to enable dark mode which seems to indicate that this label text was meant to be something else.

**Comment by nolimits4web** [comment]
fixed
