### ISSUE TITLE
cannot work, error downloading sources

### ISSUE THREAD

**Issue by cyclonmaster-zz** [framework7io/framework7-cli#5]
Hi, is this cli still working or not?
It seem that no support at all after a year.

Please advice.

**Comment by alandebortolo** [comment]
Not working here, zero bytes files.
![screenshot at may 14 15-39-21](https://user-images.githubusercontent.com/12910942/40016536-ff3ef184-578c-11e8-93cf-8f10ba5360b7.png)

**Comment by kozmanbalint** [comment]
Check v2 branch. It is in line with f7 v4.
