### ISSUE TITLE
Can't generate a release (production) apk for Android, only debug

### ISSUE THREAD

**Issue by EstebanForge** [framework7io/framework7-cli#59]
As the readme says, `npm run build-prod-cordova-android` should generate a production ready apk (Android release).
Instead, it generate an Android debug apk.

Video: https://photos.app.goo.gl/YoemuSq8nt5ev2Zm9
Up to date f7-cli.

0:52 min is the default `npm run build-prod-cordova-android`

If i try to generate a release build using just `f7 cordova build android --release` directly, using the --release flag that should be pass according to this https://cordova.apache.org/docs/en/2.7.0/guide/command-line/#android to generate a release apk, f7-cli throws an error as seen on minute 1:45 in the video:

`error: unknown option '--release'`

Screenshot: https://tppr.me/WBpQy

But if i edit the package.json and change the build-prod-cordova-android script to directly include the --release flag, then the script properly generates the release apk, as seen on minute 2:02 in the video.

Screenshot: https://tppr.me/prkw5

**Comment by EstebanForge** [comment]
Can still reproduce this on v3.2.3

**Comment by EstebanForge** [comment]
BTW, it happens with any Cordova command: https://tppr.me/zyRSC

**Comment by EstebanForge** [comment]
Updated to 3.4.2. Issue still persists:

![image](https://user-images.githubusercontent.com/1696145/87178471-2ee24b80-c2ab-11ea-8cc5-15606b53d574.png)

**Comment by nolimits4web** [comment]
It must be:
```
cd cordova && cordova build android --release
```

**Comment by EstebanForge** [comment]
Yeah, i know i can just cd into the cordova folder and run the command directly.
But since the readme says we can run cordova commands from f7-cli...

![image](https://user-images.githubusercontent.com/1696145/87179818-5d612600-c2ad-11ea-8162-c8c269e6e6bd.png)

I thought i should report this, because it doesn't work in command with flags.

But, ok i guess.

BTW,

This f7-cli usage is to compensate for another issue, but with framework7io directly. The script to build a production release in package.json is wrong.

This is a fresh f7 created app:

![image](https://user-images.githubusercontent.com/1696145/87180107-e6785d00-c2ad-11ea-9fc6-f5c6dde56b31.png)

The production build command for androids lacks the --release flag the [documentation says it should be used](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html):

![image](https://user-images.githubusercontent.com/1696145/87180476-99e15180-c2ae-11ea-852c-8e2ca80dddbd.png)

So this:

```
"build-dev-cordova-android": "cross-env TARGET=cordova cross-env NODE_ENV=development node ./build/build.js && cd cordova && cordova build android",
```

Always output an debug build. Tested in several apps using f7.

That line should be:

```
"build-dev-cordova-android": "cross-env TARGET=cordova cross-env NODE_ENV=development node ./build/build.js && cd cordova && cordova build android  --release",
```


Should i post this into https://github.com/framework7io/framework7 @nolimits4web ?
Or i'm doing something wrong?

Thanks for the time @nolimits4web
