### ISSUE TITLE
Error while creating new app

### ISSUE THREAD

**Issue by enesyurtlu** [framework7io/framework7-cli#6]
Cli created app but it return with this error. 

> ```
> Creating new Framework7 app
> Creating a new cordova project.
> Downloading scripts & hooks
>   Downloading scripts & hooks ✓
> Downloading template "tabs"
>   Downloading template "tabs" ✓
> Downloading latest version of Framework7 and icon fonts
> Response status was 404
>   framework7.ios.rtl.min.css ✓
> /usr/local/lib/node_modules/framework7-cli/node_modules/async/dist/async.js:955
>         if (fn === null) throw new Error("Callback was already called.");
>                          ^
> 
> Error: Callback was already called.
>     at /usr/local/lib/node_modules/framework7-cli/node_modules/async/dist/async.js:955:32
>     at /usr/local/lib/node_modules/framework7-cli/node_modules/async/dist/async.js:3871:13
>     at /usr/local/lib/node_modules/framework7-cli/commands.js:102:29
>     at /usr/local/lib/node_modules/framework7-cli/utils/download-framework7.js:43:33
>     at Request.<anonymous> (/usr/local/lib/node_modules/framework7-cli/utils/download.js:10:20)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at Request.onRequestResponse (/usr/local/lib/node_modules/framework7-cli/node_modules/request/request.js:1068:10)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
> ```

**Comment by kozmanbalint** [comment]
Check v2 branch. It is in line with f7 v4.
