### ISSUE TITLE
Тестирование на Windows7 темы с форума "New framework7-cli feedback needed"

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7-cli#7]
Хотел поучаствовать в http://forum.framework7.io/t/new-framework7-cli-feedback-needed/5373 но форум мне отдает 403, т.к. мой аккаунт в статусе "hold".

Система: Windows7.

1. После **npm install -g framework7-cli@beta** и запуска **framework7 create** получил: 
![2018-12-27_16-31-23](https://user-images.githubusercontent.com/1684567/50482038-c8157e00-09f5-11e9-92b9-53ab8aeed6cd.png)

2. Выполним последнюю команду из скриншота - все ок.

3. Теперь выполняю **framework7 create** Отвечаю на вопросы и в конце получаю:
![2018-12-27_16-33-28](https://user-images.githubusercontent.com/1684567/50482080-f1360e80-09f5-11e9-8037-dfe67035bc00.png)

**Comment by shastox** [comment]
При вызове команды **framework7 create --ui** и выборе / вводе настроек, зависло на таком: 
![2018-12-27_16-47-02](https://user-images.githubusercontent.com/1684567/50482331-0bbcb780-09f7-11e9-8d8e-9ab27162f1c1.png)

Но в этот раз выскочил стандартный брандмауэр с просьбой дать доступ для NodeJS (доступ я дал).

**Comment by shastox** [comment]
При исполнении команды **framework7 create --ui**, в отличие от **framework7 create**, не спрашивает Bundle ID.

**Comment by nolimits4web** [comment]
Понял, спасибо.

По поводу последнего пункта, bundle ID в UI должен спросить только когда выбрано Cordova в первом пункте

**Comment by nolimits4web** [comment]
Как это аккаунт в статусе "hold"? Что пишет? Попробуй зайти через `https`

**Comment by shastox** [comment]
![2018-12-27_17-12-47](https://user-images.githubusercontent.com/1684567/50483000-aa96e300-09fa-11e9-8d11-e31096eebaf5.png)

Попробовал через https - тоже самое.

Одно сообщение я отправил сегодня - все ок. А вот со второго получаю модальное окно с надписью "403".

**Comment by shastox** [comment]
Вот подробности:
![2018-12-27_17-14-21](https://user-images.githubusercontent.com/1684567/50483030-e0d46280-09fa-11e9-9611-904dfcfc4d5a.png)

**Comment by nolimits4web** [comment]
Так, в последней бете вроде все поправил. Нужно обновится 
```
npm i framework7-cli@beta -g
```

**Comment by nolimits4web** [comment]
Кстати с форумом должно быть ок. Я вижу что через час после этого письма он отправил письмо что аккаунт “unhold” и все ок

**Comment by shastox** [comment]
Теперь все работает.

С форумом тоже ок.

**Comment by nolimits4web** [comment]
👌
