### ISSUE TITLE
error in use

### ISSUE THREAD

**Issue by paper-me** [framework7io/framework7-cli#70]
√ All good, you have latest framework7-cli version.
? What type of the app are you targeting? PWA (Progressive Web App)
? App (project) name: My App
? What type of framework do you prefer? Framework7 with Vue.js
? Choose starter template: Split View (Split Panel)      
? Do you want to setup CSS Pre-Processor SCSS (SASS)
? Do you want to specify custom theme color? No, use default color theme
? Do you want to include Framework7 Icons and Material Icons icon fonts? Yes, include icon fonts
√ Generating package.json
√ Creating required folders structure
√ Installing NPM Dependencies
× Error installing NPM Dev Dependencies
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...738c903f7172001d60bf6'

**Comment by peterlevel1** [comment]
It would nice if adding the framework-cli version, the node version, and the npm version.

**Comment by paper-me** [comment]
I tried later, then everthing goes well. I'm new, just don't know what happened, maybe network problem? 
 Sorry. I will try and see if it can be reproduced.

**Comment by peterlevel1** [comment]
It would be good to install node packages using some mirror code ware, e.g. cnpm in China.
