### ISSUE TITLE
Capacitor Support

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-cli#75]
As a feature request I propose to support Capacitor instead of Cordova. Out of my experience it's easier for end users for the further creation of separate destination projects:

https://capacitor.ionicframework.com/

**Comment by peterlevel1** [comment]
Nice suggestion !

**Comment by D-Marc1** [comment]
Does anyone have a sample of how to use F7 with Capacitor, for the time being?

**Comment by delebash** [comment]
Any update on this question.

**Comment by D-Marc1** [comment]
@delebash I got it to work. It's not too difficult after all (though hopefully this gets built into the cli eventually). Just create a new F7 project with the CLI, but only choose browser. Then follow the [installation instructions](https://capacitorjs.com/docs/getting-started#adding-capacitor-to-an-existing-web-app) for Capacitor and it should be working.

**Comment by delebash** [comment]
Thanks

**Comment by delebash** [comment]
@D-Marc1 I tried your solution and everything looks like it installed correctly but when I run npx cap open electron electron opens but it is a blank page.  I am using the default template for the web no code changes.  When I run npm run start
the web application runs as expected.  Any ideas?

Thanks

**Comment by delebash** [comment]
@D-Marc1 Found the problem.  I took the default suggestion of using webpack however when I choose not to use webpack it worked fine. I would like to be able to use webpack as well.  Any ideas?

**Comment by D-Marc1** [comment]
@delebash You shouldn't have to remove webpack. Did you remember to run `npm run build-dev` first? That might be why it's blank for you.

**Comment by delebash** [comment]
@D-Marc1 
Tried that still no joy.  I have tried npx cap open electron still blank page, cd to electron directory and ran electron .  same result.
Any other ideas?  Thanks for your help so far.

**Comment by D-Marc1** [comment]
I updated my comment to add `-dev`. It should've been `npm run build-dev`. After doing that, you should be able to run `npm run start` to see it on your browser.

**Comment by delebash** [comment]
@D-Marc1 
I think you might be miss understanding.  I do not have a problem running it in the browser just when I try to run it in electron using npx cap open electron electron is opened but the page is blank.

**Comment by Samnan** [comment]
@delebash I recently created a new project with f7 and capacitor. I think your build path is incorrect which is why it shows blank page in electron.
To fix, first empty the `www` folder from root of project directory.
`npm run build`
check that the build files are indeed in `www` folder. If not, then fix webpack config so that the build output folder is `www` instead of `cordova/www`

after that `npx cap open electron` and see if it works.

So you have to `npm run build && npx cap open electron` each time after making changes to the app.

**Comment by scriptPilot** [comment]
What is the proposed way to use Capacitor with the latest F7 / F7 CLI version?

**Comment by nolimits4web** [comment]
Closing as Capacitor support in CLI added a while ago

**Comment by martin-braun** [comment]
@nolimits4web Could you please tell me on which version it was added? I have a very old project here that uses F7 version 2.x.x. If I upgrade F7, will a lot break?

**Comment by D-Marc1** [comment]
[According to the CHANGELOG.md, it was added in version 4.0.0](https://github.com/framework7io/framework7-cli/blob/master/CHANGELOG.md#400-beta6---december-30-2020).

**Comment by snimavat** [comment]
Would be great if docs are updated, i dont yet see capacitor in cli docs https://framework7.io/cli/
