### ISSUE TITLE
terser-webpack-plugin updated to version 5

### ISSUE THREAD

**Issue by mathsgod** [framework7io/framework7-cli#99]
terser-webpack-plugin updated to version 5, it make the build process failed

**Comment by yeshansachithak** [comment]
Yes, I had to change `"terser-webpack-plugin": "^4.2.3",` make it build

**Comment by itsthe1-apps** [comment]
I've update global npm modules and now f7-cli working without an issue. 

`npm list -g`

will list global node modules and will show the errors. In my case, I had to update `webpack` to support `terser-webpack-plugin@5.0`

`npm install -g webpack`

installed the latest webpack and now able to build
